.TH SBOUI 8
.SH NAME
sboui \- ncurses user interface for SlackBuilds.org package managers
.SH SYNOPSIS
.B sboui
[\fB\-f\fR, \fB\-\-file\fR \fIFILE\fR] 
.SH DESCRIPTION
.B sboui
is an ncurses-based user interface for
.BR sbopkg ,
.BR sbotools ,
and similar tools to build and install software from SlackBuild scripts hosted at SlackBuilds.org (SBo).
Unlike many Slackware system administration tools with 
.BR dialog -based
user interfaces,
.B sboui
is written in C++ utilizing low-level ncurses library calls.
This approach allows much greater flexibility in the design of the user interface and also makes it very fast.
The main features of
.B sboui
include:
.IP \(bu
Two-pane browsable listing of software groups and names
.IP \(bu
Filters: all, installed, upgradable, tagged, blacklisted, and non-dependencies
.IP \(bu
Search the repository, including searching in READMEs
.IP \(bu
Dependency resolution: forward and inverse mode
.IP \(bu
View and edit files in the repository
.IP \(bu
Tag multiple packages (or groups) to apply batch changes
.IP \(bu
Blacklist installed packages by name or regex pattern
.IP \(bu
Comes with several built-in color themes and supports custom themes
.IP \(bu
Designed for and tested to work flawlessly with sbopkg and sbotools, but it is easy to set it up to work with your own custom package manager
.PP
.B Instructions
.PP
Before running
.BR sboui ,
an SBo packager must first be installed.
It can be
.BR sbopkg ,
.BR sbotools ,
or a custom tool.
.B sboui
also requires a configuration file,
.I /etc/sboui/sboui.conf
(the system-wide default) or
.IR ~/.sboui.conf
(per-user override of the system-wide default).
The initial install will provide the former, while upgrades will add
.I /etc/sboui/sboui.conf.new
that the user can choose to merge with or replace the original.
See
.BR sboui.conf (5)
for more information about the configuration file.
Note also that most options can be changed at runtime in the options dialog window.
.PP
.B sboui
is a keyboard-driven program.
To switch the active pane, use the
.I Tab
key or the
.I Right
and
.I Left
arrow keys.
Use the
.I Up
and
.I Down
arrow keys,
.IR Home ,
.IR End ,
.IR PgUp ,
and 
.I PgDn
to navigate lists and dialog boxes.
When the right (or bottom, if using the vertical layout) list is active, press
.I Enter
to display possible actions for the highlighted software package.
The
.I q 
key quits the program.
The 
.I ?
key displays the full list of keyboard shortcuts.
.SH OPTIONS
Command-line options for
.B sboui
are as follows:
.TP
.BR \-f ", " \-\-file " " \fIFILE\fR
.br
Specify a configuration file other than
.I /etc/sboui/sboui.conf
or
.IR ~/.sboui.conf .
.TP
.BR \-\-help
.br
Output a usage message and exit.
.TP
.BR \-\-version
.br
Output the version number of
.B sboui
and exit.
.SH EXIT STATUS
The exit status is 0 if the command line options are valid and the configuration file was successfully read.
If invalid command line options are specified, the configuration file could not be read, or the configuration file contains errors, the exit status is 1.
Other errors that can occur during execution (e.g., a build failure for a package) are indicated to the user but do not affect the exit status.
.SH ENVIRONMENT
.TP
.B EDITOR
.br
Default editor used to view READMEs and other files, if none is specified in the configuration file.
If this environment variable is not set,
.B vi
is used as the default instead.
.SH FILES
.TP
.I /etc/sboui/sboui.conf
.br
System-wide configuration file for
.BR sboui .
See
.BR sboui.conf (5)
for more information about the entries in this file.
.TP
.I ~/.sboui.conf
.br
Per-user override of
.IR /etc/sboui/sboui.conf .
Note: this file is overwritten when settings are changed in the Options window of the user interface.
.TP
.I /etc/sboui/package_blacklist
.br
File used to blacklist installed packages.
Installed packages are searched for matches in the app name, version, arch, build, and complete package name against all patterns listed in this file.
Regex patterns are allowed.
.IP
The package_blacklist is used to prevent software from being upgraded, reinstalled, or removed, but not from being installed in the first place. 
These three actions will not be available for blacklisted packages.
They will also be excluded from the ``upgradable`` filter and included in the ``blacklisted`` filter.
.TP
Color theme files
.br
Files defining colors for different UI elements.
System color themes are stored in /usr/share/sboui/themes.
Users can also add their own color themes in $HOME/.local/share/sboui/themes.
If not present, default color settings will be used.
See
.BR sboui.conf (5)
for more information about changing color settings.
.SH BUGS
Depending on the terminal, bright background colors may not actually appear bright or may cause blinking text.
It is recommended to only use bright colors for the foreground.
.SH SEE ALSO
.BR ncurses (3X),
.BR sboui.conf (5),
.BR sbopkg (8),
.BR sboinstall (1),
.BR dialog (1),
.BR su (1)
.SH AUTHORS
Daniel Prosser <dpross1100@msn.com>
